### ISSUE TITLE
Integrating to Python Program

### ISSUE THREAD

**Issue by domzymonz** [Ersatz77/bedrock-data#1]
I just want to know, how do I integrate this to a python program? I am using `json` and `requests` module currently, and I'm very confused about the format of the command list.

**Comment by Ersatz77** [comment]
Even though this is the Bedrock command syntax, it's written in the format that the Java jar outputs when passed a few specific arguments.

It's made almost exclusively for mccq if you want to see a way to parse it:
https://github.com/Arcensoth/mccq
